### PR TITLE
added config, Interfaces, tighter scope

### PR DESCRIPTION
**Pull request by willedwards**

### CODE REVIEW

**Comment by gregturn** [comment]
This guide has been officially deprecated.

https://spring.io/blog/2016/06/02/reactor-guides-deprecated

**Comment by willedwards** [comment]
ok, what is the reason ? I couldn't see why (except the word deprecate in the title)...

**Comment by dsyer** [comment]
The article Greg linked to has a detailed explanation (TL;DR the guides are based on an outdated API and no-one wants to maintain it, so we are going to wait for the new generation of reactor before starting over).

**Comment by willedwards** [comment]
Ok got the full picture now. Thanks for your patience and clarity.

**Pull request closed without merging**
